export const WHATSAPP_NUMBER = '919398139932';

export const UI_TEXT = {
  en: {
    featuredProperties: "Featured Properties",
    featuredBlogs: "Latest From Our Blog",
    viewAllProperties: "View All Properties",
    viewAllBlogs: "View All Blogs",
    properties: "Properties",
    blogs: "Blogs",
    about: "About Us",
    home: "Home",
    filterAll: "All",
    filterPlot: "Plots",
    filterFlat: "Flats",
    filterVilla: "Villas",
    filterCommercial: "Commercial",
    filterAgricultural: "Agricultural",
    filterOthers: "Others",
    missionTitle: "Our Mission",
    missionDescription: "Unlock your financial future with real estate. Investing offers unparalleled stability, providing a tangible asset that consistently appreciates over time. Generate passive income through rentals and build substantial equity, safeguarding your wealth against inflation. It's a proven path to long-term prosperity and financial freedom, empowering you to secure a brighter tomorrow for yourself and your loved ones.",
    getInTouch: "Intrested in this property?",
    amenities: "Amenities",
    details: "Details",
    connectivity: "Connectivity",
    location: "Location",
    contactForm: {
      name: "Name",
      email: "Email",
      phone: "Phone",
      message: "Message",
      send: "Send Message",
      success: "Message sent successfully!",
      error: "Failed to send message. Please try again."
    },
    whatsapp: "Chat on WhatsApp",
    heroTitle: "",
    heroSubtitle: "",
  },
  te: {
    featuredProperties: "ఫీచర్ చేయబడిన ప్రాపర్టీలు",
    featuredBlogs: "మా బ్లాగ్ నుండి తాజావి",
    viewAllProperties: "అన్ని ప్రాపర్టీలను చూడండి",
    viewAllBlogs: "అన్ని బ్లాగులను చూడండి",
    properties: "ప్రాపర్టీలు",
    blogs: "బ్లాగులు",
    about: "మా గురించి",
    home: "హోమ్",
    filterAll: "అన్నీ",
    filterPlot: "ప్లాట్లు",
    filterFlat: "ఫ్లాట్లు",
    filterVilla: "విల్లాలు",
    filterCommercial: "కమర్షియల్",
    filterAgricultural: "వ్యవసాయ",
    filterOthers: "ఇతరులు",
    missionTitle: "మా లక్ష్యం",
    missionDescription: "రియల్ ఎస్టేట్‌తో మీ ఆర్థిక భవిష్యత్తును అన్‌లాక్ చేయండి. పెట్టుబడి అసమానమైన స్థిరత్వాన్ని అందిస్తుంది, ఇది కాలక్రమేణా స్థిరంగా ప్రశంసించబడే ప్రత్యక్ష ఆస్తిని అందిస్తుంది. అద్దెల ద్వారా నిష్క్రియాత్మక ఆదాయాన్ని సంపాదించండి మరియు ద్రవ్యోల్బణానికి వ్యతిరేకంగా మీ సంపదను కాపాడుతూ గణనీయమైన ఈక్విటీని పెంచుకోండి. ఇది దీర్ఘకాలిక శ్రేయస్సు మరియు ఆర్థిక స్వేచ్ఛకు నిరూపితమైన మార్గం, మీ కోసం మరియు మీ ప్రియమైనవారి కోసం ఉజ్వలమైన రేపటిని పొందేందుకు మీకు అధికారం ఇస్తుంది.",
    getInTouch: "ఈ ఆస్తిపై ఆసక్తి ఉందా?",
    amenities: "సౌకర్యాలు",
    details: "వివరాలు",
    connectivity: "కనెక్టివిటీ",
    location: "స్థానం",
    contactForm: {
      name: "పేరు",
      email: "ఇమెయిల్",
      phone: "ఫోన్",
      message: "సందేశం",
      send: "సందేశం పంపండి",
      success: "సందేశం విజయవంతంగా పంపబడింది!",
      error: "సందేశం పంపడంలో విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి."
    },
    whatsapp: "వాట్సాప్‌లో చాట్ చేయండి",
    heroTitle: "",
    heroSubtitle: "",
  },
};
